### PR TITLE
Switch from using ifcfg to using psutil.

### PR DESCRIPTION
**Pull request by clalancette**
This is to correspond to a change in the ros2doctor code which
does the same.

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

See https://github.com/ros2/ros2cli/pull/687 for the change we are making.

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
Hmm, unless/until we backport the switch to psutil we're going to have to make this conditional based on the rosdistro attribute. I'll propose changes to that effect.

**Comment by nuclearsandwich** [comment]
I've pushed 44785e0 to make sure we're still using ifcfg for existing ROS distros.

**Comment by clalancette** [comment]
> Hmm, unless/until we backport the switch to psutil we're going to have to make this conditional based on the rosdistro attribute. I'll propose changes to that effect.

Very excellent point, thanks for picking up on that.

**Comment by clalancette** [comment]
Just to close the loop here, this looks good to me and passes CI (see https://github.com/ros2/ci/pull/609#issuecomment-1018507224 and https://github.com/ros2/ci/pull/609#issuecomment-1018857017).  I can't approve my own PR, but take this comment as approval.  @nuclearsandwich If you want to give an approval here, I can merge in the set of changes.

**Review by nuclearsandwich — APPROVED** [review]

**Pull request merged**
