### PR TITLE
Pin EmPy to version 3.3.4.

### PR DESCRIPTION
**Pull request by clalancette**
This should fix failing builds on e.g. Humble, like https://github.com/ros2/rosbag2/pull/1829#issuecomment-2529699763

### CODE REVIEW

**Comment by clalancette** [comment]
See https://github.com/ros2/ci/pull/797#issuecomment-2532364166 for CI on this.

**Comment by cottsay** [comment]
Is the motivation a lack of EmPy 4 support? If so, I'd rather see this pinned to `<4`.

**Comment by clalancette** [comment]
> Is the motivation a lack of EmPy 4 support? If so, I'd rather see this pinned to `<4`.

Yeah, exactly, Humble doesn't have the EmPy 4 patches backported.  That's fine, I can pin it to <4.

**Review by nuclearsandwich — APPROVED** [review]

**Comment by clalancette** [comment]
In order to actually actually make this work, I had to add in additional quoting because "<" is a special redirection character on Windows cmd.  @nuclearsandwich @cottsay I could use another review here to see if what I did makes sense in https://github.com/ros-infrastructure/ros2-cookbooks/pull/78/commits/2d853ef3d45796d5602c0c855f34066cb72ce6f3 (never mind the commit message, it should have been "Add additional quotes").

**Review by cottsay — APPROVED** [review]

**Comment by clalancette** [comment]
All right, CI over in https://github.com/ros2/ci/pull/797#issuecomment-2541463359 looks good, so going ahead and merging this one.

**Pull request merged**
