### PR TITLE
Add Bison to Chocolatey installs

### PR DESCRIPTION
**Pull request by k0ekk0ek**
Reason for this PR is described in more detail [here](https://github.com/ros2/ros2_documentation/pull/1191).

Please consider pulling the changes. Thanks!

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
Looks good to me.  @k0ekk0ek Note that since this is a submodule of https://github.com/ros2/ci , you'll also have to do a PR to the ci repository to update the hash that it is pointing to.

**Comment by k0ekk0ek** [comment]
@clalancette, currently the branch `no-qt-maintenance-app` is used for the submodule. Should I just switch to `latest` there? Perhaps the `bison` dependency should be added to the `no-qt-mainenance-app` branch too?

**Comment by clalancette** [comment]
Actually, that is just a bug in the submodule documentation.  It is actually tracking latest, as you can see by the commit hash that it is using.

**Comment by k0ekk0ek** [comment]
Thank you for the info @clalancette. I commented on the respective PR already, but thank you for the information. Sorry I didn't think of that :blush:

**Pull request merged**
