### PR TITLE
Fix string slice indexing.

### PR DESCRIPTION
**Pull request by nuclearsandwich**
This was yielding 5.1.1 from 51210. Follow up to #19.

### CODE REVIEW

**Review by brawner — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
@brawner, @clalancette raised the point that the current four digit handling would misbehave if the two-digit segment was the middle rather than the last. Is there something else that will break for a Qt >= 6 so we don't have to worry (yet) about 6.1.12?

**Comment by nuclearsandwich** [comment]
Question is doubly germane as I just saw [Qt 6.0 beta4](https://lists.qt-project.org/pipermail/development/2020-November/040559.html) announced in my news feeds.

**Comment by brawner** [comment]
Will Qt6 introduce as many breaking changes as Qt5 did? Will we be using Qt5 just by the nature of how much code will need to be updated to use 6? It might be handy to filter out any versions with 6 in it, until we can officially support it. Because that logic will always choose the newest available version.

**Comment by nuclearsandwich** [comment]
>  It might be handy to filter out any versions with 6 in it, until we can officially support it.

Is that a PR you'd be able to easily make? I think it's worth doing and opening a ros2/ros2 tracking issue. I don't know that anyone has reviewed the Qt 6 changelogs. Based on past experience the transitions have been getting less disruptive. 3 to 4 required a lot of effort, 4 to 5 was much more fluid.

**Pull request merged**
